[general]
hubs_server = "dev.reticulum.io"
reticulum_server = "dev.reticulum.io"
cors_proxy_server = "cors-proxy-dev.reticulum.io"
thumbnail_server = "nearspark-dev.reticulum.io"
non_cors_proxy_domains = "hubs.local,dev.reticulum.io"
base_assets_path = "/"
sentry_dsn = ""
ga_tracking_id = ""
is_moz = false

[deploy]
type = "none"
